### ISSUE TITLE
 fatal error: sys/socket.h: No such file or directory  #include <sys/socket.h>

### ISSUE THREAD

**Issue by rv0710** [halloweeks/networking#4]
fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>

ANY solution

**Comment by halloweeks** [comment]
For a Linux-based system, the error indicates that the necessary development package for system headers is missing. You can typically resolve this by installing the relevant package. Try the following command:

```bash
sudo apt-get install build-essential
```

This command installs essential development tools, including the required header files like `sys/socket.h`. After running this, attempt to compile your code again.
